### ISSUE TITLE
COC link not working

### ISSUE THREAD

**Issue by theaverageguy** [pythonindia/inpycon2016#1]
Hey! 
The COC link is not working. Might as well comment it out till we add the page.

**Comment by dhuadaar** [comment]
I removed the following class and things worked. Any ideas what could be issue. Couldn't find a caveat in the CSS though.

<ul class="py16navbar nav navbar-nav">

**Comment by theskumar** [comment]
I'll check and enable COC if things look good.

**Comment by dhuadaar** [comment]
Also

If we are not able to debug this, I think we can make a modal for the COC
as we did in the PyDelhiConf website
