### ISSUE TITLE
Wrong dates on cfp

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/inpycon2016#22]
CFP page is showing conf. dates instead of actual dates.

![b](https://cloud.githubusercontent.com/assets/4463796/13959875/e2a6f172-f07b-11e5-8505-afbe8e121ccb.png)

Also change title to something like `PyCon India 2016` instead of `2016`.

**Comment by theskumar** [comment]
This should be resolved now, @ChillarAnand please reopen if you still see an issue.
