### ISSUE TITLE
Blog issue

### ISSUE THREAD

**Issue by dhuadaar** [pythonindia/inpycon2016#26]
Accessing blog from the link 

[https://in.pycon.org/blog/]
This routes me to the last year's website. The navbar at this page navigates through website of PyCon 2015. 

Needs to be fixed.

**Comment by kracekumar** [comment]
When first blog post is pushed, the new one will appear. Also you can hard code link to blog as `https://in.pycon.org/blog/2016/` once initial post is pushed.
