### ISSUE TITLE
Scrolling on clicking Navbar links

### ISSUE THREAD

**Issue by ankur0493** [pythonindia/inpycon2016#28]
The automatic scrolling that happens when any Navbar link is too slow and sometimes lags behind the clicks. 
Suggest changing the `duration` value from current `2500` to `700` or `800`. Can submit a PR if this sounds fine.

**Comment by userimack** [comment]
Hello I have submitted a pr for this issue, https://github.com/pythonindia/inpycon2016/pull/29
