### ISSUE TITLE
Keynote Speakers in Left sidebar

### ISSUE THREAD

**Issue by aktech** [pythonindia/inpycon2016#59]
The left navigation is kind of weird, After **HOME** it skips Keynote Speakers and straightway mentions **VENUE**, There should be Keynote Speaker in between. Probably Something less significant could be removed to incorporate that.

**Comment by satyaakam** [comment]
@aktech  this is where the @CuriousLearner worked on creating a carousal check his PR is this something you are looking for ?

**Comment by aktech** [comment]
@satyaakam I mean there should be a link for Keynotes on left sidebar, just above Venue to maintain consistency:

<img width="251" alt="screen shot 2016-07-31 at 9 53 56 am" src="https://cloud.githubusercontent.com/assets/5647941/17274565/eaeabd4c-5704-11e6-8cd1-6bc91b8a0165.png">

**Comment by bhanuvrat** [comment]
closing the ticket.
this has been done.
