### ISSUE TITLE
UI/mobile: Fix color of footer links in mobile views.

### ISSUE THREAD

**Issue by theskumar** [pythonindia/inpycon2016#76]
![a](https://www.dropbox.com/s/e1p9igrlo8ni6m2/Screenshot%202016-09-01%2015.09.27.jpg?dl=1)

**Comment by vikalpj** [comment]
@mayank-shekhar can you look at this when you get time today or tomorrow?

**Comment by mayank-shekhar** [comment]
@vikalpj sure

**Comment by theskumar** [comment]
This is done in #79, thanks a lot @mayank-shekhar !
