### ISSUE TITLE
Pipal Academy as associate sponsor

### ISSUE THREAD

**Issue by bhanuvrat** [pythonindia/inpycon2016#82]
The below mentioned quote and image has to be added to the sponsors section.
in a new head called Associate Sponsor, which is to be smaller in comparison to Silver Sponsors.
"""
Pipal Academy is a collective of experienced technologists, who care deeply about the art of software development. We offer in-depth courses on niche technical topics.

We regularly conduct public workshops in Bangalore and also offer
on site corporate trainings. Our courses are targeted at professional software developers and we make sure they are hands-on and interactive. 
"""

![pipal-logo2](https://cloud.githubusercontent.com/assets/499894/18298284/0f3cdbd8-74d5-11e6-8e8f-c4795ec6bda1.png)

**Comment by pushplataranjan** [comment]
pull request #83 : Added Pipal Academy details.

**Comment by akshayaurora** [comment]
closed by #83
